//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Exam_System_DBEntities : DbContext
    {
        public Exam_System_DBEntities()
            : base("name=Exam_System_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Admin> Tbl_Admin { get; set; }
        public virtual DbSet<Tbl_Answer> Tbl_Answer { get; set; }
        public virtual DbSet<Tbl_chapter> Tbl_chapter { get; set; }
        public virtual DbSet<Tbl_department> Tbl_department { get; set; }
        public virtual DbSet<Tbl_Level> Tbl_Level { get; set; }
        public virtual DbSet<Tbl_Prof> Tbl_Prof { get; set; }
        public virtual DbSet<Tbl_Question> Tbl_Question { get; set; }
        public virtual DbSet<Tbl_Result> Tbl_Result { get; set; }
        public virtual DbSet<Tbl_Student> Tbl_Student { get; set; }
        public virtual DbSet<Tbl_Subject> Tbl_Subject { get; set; }
        public virtual DbSet<Tbl_ExamStructure> Tbl_ExamStructure { get; set; }
    }
}
