//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_department()
        {
            this.Tbl_Subject = new HashSet<Tbl_Subject>();
        }
    
        public int Department_ID { get; set; }
        public string Name_Ar { get; set; }
        public string Name_En { get; set; }
        public int Level_ID { get; set; }
    
        public virtual Tbl_Level Tbl_Level { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Subject> Tbl_Subject { get; set; }
    }
}
