//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_chapter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_chapter()
        {
            this.Tbl_Question = new HashSet<Tbl_Question>();
            this.Tbl_ExamStructure = new HashSet<Tbl_ExamStructure>();
        }
    
        public int Chapter_ID { get; set; }
        public string Name_Ar { get; set; }
        public string Name_En { get; set; }
        public int Subject_ID { get; set; }
    
        public virtual Tbl_Subject Tbl_Subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Question> Tbl_Question { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ExamStructure> Tbl_ExamStructure { get; set; }
    }
}
